"""
Project Phoenix
Milestone M14 - AI Decision Engine

Module:
    ai_models.py

Purpose:
    Defines all data models used by the
    AI Decision Engine.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Dict, Optional


class AIDecisionStatus(Enum):
    """
    Final AI decision status.
    """

    APPROVE = "APPROVE"

    REJECT = "REJECT"


@dataclass
class AIContext:
    """
    Context received by the AI Engine.
    """

    signal_strength: float

    risk_score: float

    performance_score: float

    portfolio_score: float

    optimization_score: float

    metadata: Dict[str, Any] = field(
        default_factory=dict
    )


@dataclass
class AIRecommendation:
    """
    Recommendation generated by the AI Engine.
    """

    decision: AIDecisionStatus

    confidence: float

    score: float

    reason: str


@dataclass
class AIDecision:
    """
    Final AI decision.
    """

    recommendation: AIRecommendation

    approved: bool

    reason: Optional[str] = None