"""
Project Phoenix
Milestone M8 - Signal Generation Engine

Module:
    signal_models.py

Purpose:
    Defines all core data models used by the Signal Generation Engine.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Dict, List, Optional


class SignalType(Enum):
    """
    Final trading signal produced by the Signal Engine.
    """

    BUY = "BUY"
    SELL = "SELL"
    HOLD = "HOLD"


class RuleDirection(Enum):
    """
    Direction returned by an individual trading rule.
    """

    BULLISH = "BULLISH"
    BEARISH = "BEARISH"
    NEUTRAL = "NEUTRAL"


@dataclass
class RuleResult:
    """
    Result produced by a single trading rule.
    """

    rule_name: str
    direction: RuleDirection
    strength: float
    passed: bool
    reason: Optional[str] = None


@dataclass
class TradingSignal:
    """
    Final trading signal generated by the Signal Engine.
    """

    signal: SignalType
    strength: float
    confidence: float

    rules: List[RuleResult] = field(default_factory=list)

    reason: str = ""

    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class SignalContext:
    """
    Context information used while generating a signal.
    """

    symbol: str
    timeframe: str

    price: float = 0.0

    indicators: Dict[str, Any] = field(default_factory=dict)

    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class ValidationResult:
    """
    Result returned by the signal validator.
    """

    valid: bool

    score: float = 0.0

    reason: Optional[str] = None


@dataclass
class FilterResult:
    """
    Result returned by the signal filter stage.
    """

    accepted: bool

    reason: Optional[str] = None