"""
Project Phoenix
Milestone M17 - Learning Engine

Module:
    learning_models.py

Purpose:
    Defines all core data models used by the
    Learning Engine.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Dict, Optional


class LearningStatus(Enum):
    """
    Final learning status.
    """

    APPROVED = "APPROVED"

    REJECTED = "REJECTED"


@dataclass
class LearningPattern:
    """
    Represents a detected trading pattern.
    """

    pattern_name: str

    confidence: float

    occurrences: int

    description: str


@dataclass
class LearningRecommendation:
    """
    Recommendation generated by the
    Learning Engine.
    """

    recommendation_type: str

    current_value: float

    suggested_value: float

    confidence: float

    reason: str


@dataclass
class LearningContext:
    """
    Context supplied to the Learning Engine.
    """

    strategy_name: str

    total_trades: int

    win_rate: float

    profit_factor: float

    metadata: Dict[str, Any] = field(
        default_factory=dict
    )


@dataclass
class LearningDecision:
    """
    Final output of the Learning Engine.
    """

    status: LearningStatus

    pattern: LearningPattern

    recommendation: LearningRecommendation

    approved: bool

    reason: Optional[str] = None